name: Build and Deploy Flutter App

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Allow GitHub Actions to create and push tags

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history to allow tagging

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'

      - name: Install Dart 3.7.0
        uses: dart-lang/setup-dart@v1
        with:
          sdk: '3.7.0'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Create Git Tag
        run: |
          TAG_NAME="v$(date +'%Y%m%d%H%M%S')"  # Format: vYYYYMMDDHHMMSS
          echo "Tagging with $TAG_NAME"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git tag $TAG_NAME
          git push origin $TAG_NAME

      - name: Upload APK to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
