name: Build and Distribute Flutter App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter (latest stable)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'  # Use latest stable version
          channel: stable

      - name: Verify Dart Version
        run: dart --version  # Check installed Dart version

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsJson: ${{ secrets.FIREBASE_SA_KEY }}
          groups: testers
          file: build/app/outputs/flutter-apk/app-release.apk
